### ISSUE TITLE
Send & Receive Images

### ISSUE THREAD

**Issue by itsjoekent** [DoSomething/jarvis#4]
Handle images in each reciever.

### Twilio 
https://www.twilio.com/docs/api/rest/sending-messages
```js
client.messages.create({ 
    to: "+15558675309", 
    from: "+15017250604", 
    body: "This is the ship that made the Kessel Run in fourteen parsecs?", 
    mediaUrl: "https://c1.staticflickr.com/3/2899/14341091933_1e92e62d12_b.jpg",  
}, function(err, message) { 
    console.log(message.sid); 
});
```

### MoCo
https://community.uplandsoftware.com/hc/en-us/articles/204494185-REST-API#SendMMSMessage
```
campaign_id
body (160 characters or fewer. If passing body as a URL param, the value must be URL encoded)
phone_number
attachment_id (*Optional id of attachment to be included with the message)
uploaded_attachment (*Optional multi-part supported image to be sent)
```

**Comment by itsjoekent** [comment]
Seems like Twilio only supports 1 media url. 

Also sending multiple media in a single message seems crazy for SMS users anyway... Going to just make that a string field instead of an array.

**Comment by deadlybutter** [comment]
Just documenting here for the moment, URL's from Reddit/Imgur don't work with Twilio, but Flickr does. Not sure why, I'm assuming some websites are disabling crawling or something?

**Comment by itsjoekent** [comment]
https://github.com/DoSomething/jarvis/commit/1c8337da12025986ca57dccd778b8162e5013c2a
